version: '2'

services:
    postgres:
        restart: always
        image: postgres:9.5-alpine
        expose:
            - "5432"
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - variables.env
    php:
        build:
            context: php7-apache
            args:
                TIMEZONE: Europe/Paris
        ports:
            - "80:80"
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        env_file:
            - variables.env
    # nginx:
    #     build: nginx
    #     ports:
    #         - 80:80
    #         - 443:443
    #     volumes_from:
    #         - php
    #     volumes:
    #         - ./logs/nginx/:/var/log/nginx

volumes:
  postgres:
    driver: local
