# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "www/src/assets"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "www/src/**/*"
    - "!www/src/{img,js,scss,html}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "www/src/sass"
  # Paths to JavaScript libraries, which are compined into one file
  # javascript:
    # Libraries requried by Foundation
    # - "bower_components/jquery/dist/jquery.js"
    # - "bower_components/what-input/what-input.js"
    # # Core Foundation files
    # - "bower_components/foundation-sites/dist/plugins/foundation.core.js"
    # - "bower_components/foundation-sites/dist/plugins/foundation.util.*.js"
    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    # - "bower_components/foundation-sites/js/foundation.abide.js"
    # - "bower_components/foundation-sites/js/foundation.accordion.js"
    # - "bower_components/foundation-sites/js/foundation.accordionMenu.js"
    # - "bower_components/foundation-sites/js/foundation.drilldown.js"
    # - "bower_components/foundation-sites/js/foundation.dropdown.js"
    # - "bower_components/foundation-sites/js/foundation.dropdownMenu.js"
    # - "bower_components/foundation-sites/js/foundation.equalizer.js"
    # - "bower_components/foundation-sites/js/foundation.interchange.js"
    # - "bower_components/foundation-sites/js/foundation.magellan.js"
    # - "bower_components/foundation-sites/js/foundation.offcanvas.js"
    # - "bower_components/foundation-sites/js/foundation.orbit.js"
    # - "bower_components/foundation-sites/js/foundation.responsiveMenu.js"
    # - "bower_components/foundation-sites/js/foundation.responsiveToggle.js"
    # - "bower_components/foundation-sites/js/foundation.reveal.js"
    # - "bower_components/foundation-sites/js/foundation.slider.js"
    # - "bower_components/foundation-sites/js/foundation.sticky.js"
    # - "bower_components/foundation-sites/js/foundation.tabs.js"
    # - "bower_components/foundation-sites/js/foundation.toggler.js"
    # - "bower_components/foundation-sites/js/foundation.tooltip.js"
    # Paths to your own project code are here
    # - "src/js/lib/bg.lazyload.js"
    # - "src/js/lib/jquery.lazyloadxt.js"
    # - "src/js/lib/jquery.lazyloadxt.srcset.js"
    # - "src/js/lib/jquery.lazyloadxt.bg.js"
    # - "src/js/lib/jquery.lazyloadxt.video.js"
    # - "src/js/!(app).js"
    # - "src/js/app.js"
